### ISSUE TITLE
Multiple issues with RPC on Testnet

### ISSUE THREAD

**Issue by alexauroradev** [aurora-is-near/aurora-relayer#136]
I've been adding Aurora network to Rarible contracts: https://github.com/djsatok/protocol-contracts
The call
```
$ truffle test --compile-all --network aurora  
```
Results in long tests, missing events and other problems

<img width="675" alt="Screenshot 2021-12-07 at 23 30 47" src="https://user-images.githubusercontent.com/5417224/145109128-794e8d23-67aa-460c-bcf9-c02d7f9e9fcf.png">

**Comment by SouadAli10** [comment]
@alexauroradev @antonpaisov  for this issue here is what I got from debugging the issue 

```
Node 14.18.2
npm 6.14.15
Truffle v5.4.26 (core: 5.4.26)
Solidity - 0.7.6 (solc-js)
Node v14.18.2
Web3.js v1.5.3
```

Running these tests without pointing towards Aurora is not showing any error, when using the Broken-Line folder.

When adding the aurora configs 
``` networks: {
    e2e: createNetwork("e2e"),
    ops: createNetwork("ops"),
    ropsten: createNetwork("ropsten"),
    mainnet: createNetwork("mainnet"),
    rinkeby: createNetwork("rinkeby"),
    rinkeby2: createNetwork("rinkeby2"),
    polygon_mumbai: createNetwork("polygon_mumbai"),
	aurora: {
      provider: () => setupWallet('https://testnet.aurora.dev/AiHEfCXeLBqodUosBPeddiTpJNfUHbRdx2aZEKMnsit1', '9d34444b91bf3bac70d7d89edad0c38295fd452078420255ff1f3631089d6af5'),
      network_id: 0x4e454153,
      gas: 10000000,
	  gasPrice: "0",
      from: '0x109E7E98DE7a6572948009f8733bbbd56f146fB1'
    }
  },```

When running against testnet some of the tests are failing 
```Compiled successfully using:
   - solc: 0.7.6+commit.7338295f.Emscripten.clang


> Duplicate contract names found for LibIntMapping.
> This can cause errors and unknown behavior. Please rename one of your contracts.


  Contract: BrokenLine
    Check add()
      ✓ Should update if no line added (12300ms)
      ✓ One line can be added, tail works (38249ms)
      ✓ One line with no mod should work (37745ms)
      1) Some lines can be added at one time
    > No events were emitted
      2) Check line.bias == line.slope with cliff
    > No events were emitted
      3) Add line with the same id, expect throw 
    > No events were emitted
      4) "before each" hook for "Add line with slope == 0, expect throw "


  3 passing (8m)
  4 failing

  1) Contract: BrokenLine
       Check add()
         Some lines can be added at one time:
     AssertionError: expected '3' to equal 4
      at assertCurrent (test/BrokenLine.test.js:9:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at Context.<anonymous> (test/BrokenLine.test.js:81:4)

  2) Contract: BrokenLine
       Check add()
         Check line.bias == line.slope with cliff:
     AssertionError: expected '3' to equal 4
      at assertCurrent (test/BrokenLine.test.js:9:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at Context.<anonymous> (test/BrokenLine.test.js:98:4)

  3) Contract: BrokenLine
       Check add()
         Add line with the same id, expect throw :
     AssertionError: Expected throw not received
      at module.exports.expectThrow (/Users/souadali/Desktop/Work/Aurora/protocol-contracts/node_modules/@daonomic/tests-common/index.js:54:3)
      at runNextTicks (internal/process/task_queues.js:60:5)
      at listOnTimeout (internal/timers.js:526:9)
      at processTimers (internal/timers.js:500:7)
      at Context.<anonymous> (test/BrokenLine.test.js:105:4)

  4) Contract: BrokenLine
       "before each" hook for "Add line with slope == 0, expect throw ":
     Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/souadali/Desktop/Work/Aurora/protocol-contracts/broken-line/test/BrokenLine.test.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

But Running the tests against the mainnet has caused an error in running the tests 
```Promise {
  <rejected> {
    code: -32603,
    message: 'getaddrinfo ENOTFOUND mainnet.aurora.dev',
    data: { originalError: [Object] },
    stack: 'Error: getaddrinfo ENOTFOUND mainnet.aurora.dev\n' +
      '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)'
  }
} {
  code: -32603,
  message: 'getaddrinfo ENOTFOUND mainnet.aurora.dev',
  data: {
    originalError: {
      errno: -3008,
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'mainnet.aurora.dev'
    }
  },
  stack: 'Error: getaddrinfo ENOTFOUND mainnet.aurora.dev\n' +
    '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)'
}
Promise {
  <rejected> {
    code: -32603,
    message: 'getaddrinfo ENOTFOUND mainnet.aurora.dev',
    data: { originalError: [Object] },
    stack: 'Error: getaddrinfo ENOTFOUND mainnet.aurora.dev\n' +
      '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)'
  }
} {
  code: -32603,
  message: 'getaddrinfo ENOTFOUND mainnet.aurora.dev',
  data: {
    originalError: {
      errno: -3008,
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'mainnet.aurora.dev'
    }
  },
  stack: 'Error: getaddrinfo ENOTFOUND mainnet.aurora.dev\n' +
    '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)'
}
Promise {
  <rejected> {
    code: -32603,
    message: 'getaddrinfo ENOTFOUND mainnet.aurora.dev',
    data: { originalError: [Object] },
    stack: 'Error: getaddrinfo ENOTFOUND mainnet.aurora.dev\n' +
      '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)'
  }
} {
  code: -32603,
  message: 'getaddrinfo ENOTFOUND mainnet.aurora.dev',
  data: {
    originalError: {
      errno: -3008,
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'mainnet.aurora.dev'
    }
  },
  stack: 'Error: getaddrinfo ENOTFOUND mainnet.aurora.dev\n' +
    '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)'
}
Promise {
  <rejected> {
    code: -32603,
    message: 'getaddrinfo ENOTFOUND mainnet.aurora.dev',
    data: { originalError: [Object] },
    stack: 'Error: getaddrinfo ENOTFOUND mainnet.aurora.dev\n' +
      '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)'
  }
} {
  code: -32603,
  message: 'getaddrinfo ENOTFOUND mainnet.aurora.dev',
  data: {
    originalError: {
      errno: -3008,
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'mainnet.aurora.dev'
    }
  },
  stack: 'Error: getaddrinfo ENOTFOUND mainnet.aurora.dev\n' +
    '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)'
}```

**Comment by NanezX** [comment]
With hardhat i got an issue with the RPC too: "**HardhatError: HH110: Invalid JSON-RPC response received:**"
And this is my Hardhat config:
```
aurora_testnet: {
   url: "https://testnet.aurora.dev/",
   chainId: 1313161555,
   accounts: process.env.MNEMONIC !== undefined ? {mnemonic: process.env.MNEMONIC} : [process.env.PRIVATE_KEY],
   gasPrice: 0
}
```

**Comment by 0x3bfc** [comment]
@NanezX Is it related to the Rarible contracts unit tests issue? If it is a different issue, please open a new one stating the steps to reproduce your problem.

**Comment by antonpaisov** [comment]
the tests are focused to be running on hardhat, they even fail on Rinkeby, without fiddling with the delays.
It's not specific to Aurora testnet.
