### ISSUE TITLE
error: relation "subscription" does not exist

### ISSUE THREAD

**Issue by chaishiqi** [aurora-is-near/aurora-relayer#146]
I have downloaded the image [ auroraisnear/relayer-endpoint:mainnet](https://hub.docker.com/r/auroraisnear/relayer-endpoint/tags) by dockerhub. When running with docker-compose,some problem occured like below:

```
/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:287
        const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                 ^

error: relation "subscription" does not exist
    at Parser.parseErrorMessage (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/srv/aurora/relayer/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) 
```

how to resolve it?

**Comment by 0x3bfc** [comment]
From [CHANGELOG.md](https://github.com/aurora-is-near/aurora-relayer/blob/master/CHANGES.md)


New table to handle subscriptions. To update your existing schema, execute:

```CREATE TABLE subscription (
	sec_websocket_key varchar COLLATE "default",
	id                varchar COLLATE "default",
	type              varchar COLLATE "default",
	ip                varchar COLLATE "default",
	filter            jsonb NULL
);

CREATE UNIQUE INDEX subscription_sec_websocket_key_type_filter_index_idx ON subscription (sec_websocket_key, type, filter);
```
