### ISSUE TITLE
near key pair loaded but no matching key pair found by endpoint

### ISSUE THREAD

**Issue by lcgogo** [aurora-is-near/aurora-relayer#154]
I place the keypair in /.near-credentials/mainnet/aurora.json and the log shows it loaded.

```shell
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
{"level":30,"time":1640790123224,"pid":7,"hostname":"9abc9d5c4ca9","msg":"starting server"}
Loaded signer key file /.near-credentials/mainnet/aurora.json.
{"level":30,"time":1640790127128,"pid":7,"hostname":"9abc9d5c4ca9","req":{"id":"kjQNntcB8mMjcTNq","method":"POST","url":"/","headers":{"host":"aurora.rpc.one","user-agent":"BlockchainAgent","connection":"close, keep-alive","content-length":"70","accept":"application/json","accept-encoding":"gzip, deflate","content-type":"application/json","sentry-trace":"35eec1956d584ea89b908388417b1010-b0a1e7c36c9437cd-"},"remoteAddress":"::ffff:172.25.4.60","remotePort":49668},"rpc":{"method":"eth_blockNumber","params":[]},"res":{"statusCode":200,"headers":{"x-request-id":"kjQNntcB8mMjcTNq","access-control-allow-origin":"*","content-length":45,"content-type":"application/json; charset=utf-8"}},"responseTime":169,"msg":"request completed"}
```

However when try to send transaction, the endpoint met followed error that no matching key pair.

```shell
TypedError: Can not sign transactions for account aurora on network mainnet, no matching key pair found in InMemorySigner(MergeKeyStore(InMemoryMultiKeyStore, InMemoryKeyStore, UnencryptedFileSystemKeyStore(/.near-credentials))).
    at Account.signTransaction (/srv/aurora/relayer/node_modules/near-api-js/lib/account.js:74:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /srv/aurora/relayer/node_modules/near-api-js/lib/account.js:91:34
    at async Object.exponentialBackoff [as default] (/srv/aurora/relayer/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async Account.signAndSendTransaction (/srv/aurora/relayer/node_modules/near-api-js/lib/account.js:90:24)
    at async Engine.callMutativeFunction (file:///srv/aurora/relayer/node_modules/@aurora-is-near/engine/lib/engine.js:313:28)
    at async Engine.submit (file:///srv/aurora/relayer/node_modules/@aurora-is-near/engine/lib/engine.js:192:21)
    at async DatabaseServer.eth_sendRawTransaction (file:///srv/aurora/relayer/lib/servers/database.js:424:17) {
  type: 'KeyNotFound',
  context: undefined
}
{"level":50,"time":1640806624487,"pid":7,"hostname":"9abc9d5c4ca9","code":-32603,"stack":"Error: Error: Can not sign transactions for account aurora on network mainnet, no matching key pair found in InMemorySigner(MergeKeyStore(InMemoryMultiKeyStore, InMemoryKeyStore, UnencryptedFileSystemKeyStore(/.near-credentials))).\n    at Object.err (file:///srv/aurora/relayer/lib/servers/database.js:457:35)\n    at Object.match (/srv/aurora/relayer/node_modules/@hqoss/monads/dist/lib/result/result.js:82:32)\n    at DatabaseServer.eth_sendRawTransaction (file:///srv/aurora/relayer/lib/servers/database.js:424:61)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","type":"Error","msg":"Error: Can not sign transactions for account aurora on network mainnet, no matching key pair found in InMemorySigner(MergeKeyStore(InMemoryMultiKeyStore, InMemoryKeyStore, UnencryptedFileSystemKeyStore(/.near-credentials)))."}
```

**Comment by lcgogo** [comment]
my json file is create by
```shell
export NEAR_ENV=mainnet
near generate-key aurora
cat ~/.near-credentials/mainnet/aurora.json
```
Then put it to the running docker

**Comment by lcgogo** [comment]
@artob @spilin @0x3bfc Can you help to figure out how to fill the mainnet signer config?

**Comment by 0x3bfc** [comment]
@lcgogo can you share the content of [mainnet.yaml](https://github.com/aurora-is-near/aurora-relayer/blob/master/config/mainnet.yaml) ?

**Comment by JonathanLogan** [comment]
@lcgogo : Assuming you run this from the docker-compose coonfig.
Place your key into the config/ volume and reference it from the mainnet.yaml like this:

`signerKeys:
  - config/keyfile.json
`
Also set the signer entry to the name of the key. You'll also have to set "writable" to true.

That said, the keyfile MUST refer to an account on NEAR, not just a locally generated keypair. Only an account will be able to actually sign a transaction.
