### ISSUE TITLE
DB Not Found Error when trying to interact with contract

### ISSUE THREAD

**Issue by mradmilovic** [aurora-is-near/aurora-relayer#163]
Sometimes I am getting this error when trying to interact with my contracts on Aurora testnet. Seems to me that this is not from our side.

`{
code: -32603, 
message: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 79333079 \n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"relayer01.us.testnet.backend.aurora.dev","cf-ray":"6cf7721d27ddcbb0-IAD"}}}}', 
stack: 
{
  "code": -32603,
  "message": "[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32603,\"message\":\"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 79333079 \\n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>\",\"data\":{\"host\":\"relayer01.us.testnet.backend.aurora.dev\",\"cf-ray\":\"6cf7721d27ddcbb0-IAD\"}}}}'",
  "stack": "Error: [ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32603,\"message\":\"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 79333079 \\n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>\",\"data\":{\"host\":\"relayer01.us.testnet.backend.aurora.dev\",\"cf-ray\":\"6cf7721d27ddcbb0-IAD\"}}}}'\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\n    at y.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:210928)\n    at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:35204)\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:117610)\n    at y.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:118146)\n    at y._setTransactionStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:46740)\n    at y.setTxStatusFailed (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:45972)\n    at B._failTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:225990)\n    at B.approveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:217659)\n    at async B.updateAndApproveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:216902)"
}
  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)
  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)
  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)
  at y.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:210928)
  at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:35204)
  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:117610)
  at y.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:118146)
  at y._setTransactionStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:46740)
  at y.setTxStatusFailed (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:45972)
  at B._failTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:225990)
  at B.approveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:217659)
  at async B.updateAndApproveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:216902)
}`

**Comment by spilin** [comment]
Hi. We are aware of this issue and it is being addressed.
Can you please provide some additional information on your interaction. Ideally steps to reproduce would be great.
Tnx in advance.

**Comment by bombermine3** [comment]
Same here whet trying to swap AUSD to MEME

Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 83510172 \n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r001.eastcoast.us.testnet.internal.aurora.dev","cf-ray":"6e1f69f600e1359b-IAD"}}}}'

**Comment by bombermine3** [comment]
But the next attempt went without errors. https://testnet.aurorascan.dev/tx/0x87ecdb0c3284e18565c177c4867e03fe8cf37a2c2653a496d423fac8cd899841

**Comment by spilin** [comment]
This issue should be resolved by now. Please reopen if it reoccurs again.
