### ISSUE TITLE
RPC not working

### ISSUE THREAD

**Issue by PauloAMFaria** [aurora-is-near/aurora-relayer#174]
I have been using 'https://mainnet.aurora.dev' for a month without a problem but since 22/01/2022 it stopped working using web3.js library, some basic functions getting error:
Returned error: Unsupported method: eth_getTransactionCount
and
Returned error: Unsupported method: eth_getBalance

**Comment by spilin** [comment]
What kind of transaction did you want to make? You might have fallen victim of anti-abuse measures.

**Comment by PauloAMFaria** [comment]
I already got that before and the error was "Invalid JSON RPC response: "error code: 1020".

Now it is different, I have errors in specific methods:
I can for example interact with my smart contracts or a token contract and make a call()
Ex: new web3.eth.Contract(TOKEN_ABI, tokenAddress); tokenContract.methods.balanceOf(walletAddress); ✅
but a send() would fail.

Other 2 methods that are failing for me are the ones mentioned above:

web3.eth.getBalance(walletAddress); 
Error: Returned error: Unsupported method: eth_getBalance
    at Object.ErrorResponse (....../node_modules/web3-core-helpers/lib/errors.js:28:19)
    at ...../node_modules/web3-core-requestmanager/lib/index.js:302:36
    at XMLHttpRequest.request.onreadystatechange (...../node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (....../node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (....../node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (....../node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/....../node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1340:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  data: {
    host: 'relayer009.east.us.backend.internal.aurora.dev',
    'cf-ray': '6d3128c2173703f6-LIS'
  }
}

and

web3.eth.getTransactionCount(walletAddress)
Error: Returned error: Unsupported method: eth_getTransactionCount
    at Object.ErrorResponse (...../node_modules/web3-core-helpers/lib/errors.js:28:19)
    at ....../node_modules/web3-core-requestmanager/lib/index.js:302:36
    at XMLHttpRequest.request.onreadystatechange (...../node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (...../node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (...../node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (....../node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (..../node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1340:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  data: {
    host: 'relayer009.east.us.backend.internal.aurora.dev',
    'cf-ray': '6d31316437c003ea-IAD'
  }
}

**Comment by antonpaisov** [comment]
hey @PauloAMFaria 
can you send me your IP address in direct message in TG (@antonpaisov) or via email, or any other convenient way?
I will check if you got blocked and can help you out if the issue remains.
