### ISSUE TITLE
DB errors while running the partner-relayer-deploy docker image

### ISSUE THREAD

**Issue by mcf-rocks** [aurora-is-near/aurora-relayer#181]
```Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_database | 2022-02-13 18:53:23.468 UTC [36] ERROR:  duplicate key value violates unique constraint "block_pkey"
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_database | 2022-02-13 18:53:23.468 UTC [36] DETAIL:  Key (id)=(59151666) already exists.
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_database | 2022-02-13 18:53:23.468 UTC [36] STATEMENT:  INSERT INTO block (chain, id, hash, near_hash, timestamp, size, gas_limit, gas_used, parent_hash, transactions_root, state_root, receipts_root) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer | indexBlock error: duplicate key value violates unique constraint "block_pkey"
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |     at Parser.parseErrorMessage (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:287:98)
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |     at Parser.handlePacket (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:126:29)
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |     at Parser.parse (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:39:38)
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |     at Socket.<anonymous> (/srv/aurora/relayer/node_modules/pg-protocol/dist/index.js:11:42)
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |     at Socket.emit (node:events:390:28)
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |     at addChunk (node:internal/streams/readable:315:12)
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |     at readableAddChunk (node:internal/streams/readable:289:9)
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |     at Socket.Readable.push (node:internal/streams/readable:228:10)
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |     at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   length: 187,
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   severity: 'ERROR',
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   code: '23505',
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   detail: 'Key (id)=(59151666) already exists.',
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   hint: undefined,
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   position: undefined,
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   internalPosition: undefined,
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   internalQuery: undefined,
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   where: undefined,
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   schema: 'public',
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   table: 'block',
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   column: undefined,
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   dataType: undefined,
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   constraint: 'block_pkey',
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   file: 'nbtinsert.c',
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   line: '649',
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer |   routine: '_bt_check_unique'
Feb 13 18:53:23 midget docker-compose[3351132]: mainnet_indexer | }```

**Comment by mcf-rocks** [comment]
add "ignore dups" to your SQL to avoid this.

**Comment by spilin** [comment]
@mcf-rocks We released an update that should resolve this issue. Please reopen if it will reoccur.
