### ISSUE TITLE
`eth_getFilterChanges` incorrectly returns `data: null`

### ISSUE THREAD

**Issue by 0x3bfc** [aurora-is-near/aurora-relayer#19]
The data field in the result of `eth_getFilterChanges` should contain one or more 32 Bytes non-indexed arguments of the log.

## Example

```
{
    "logIndex": "0x1", // 1
    "blockNumber":"0x1b4", // 436
    "blockHash": "0x8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcfdf829c5a142f1fccd7d",
    "transactionHash":  "0xdf829c5a142f1fccd7d8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcf",
    "transactionIndex": "0x0", // 0
    "address": "0x16c5785ac562ff41e2dcfdf829c5a142f1fccd7d",
    "data":"0x0000000000000000000000000000000000000000000000000000000000000000",
    "topics": ["0x59ebeb90bc63057b6515673c3ecf9438e5058bca0f92585014eced636878c9a5"]
    }
```

What I got from the RPC relayer:
```
{
  blockNumber: '0x30743d5',
  blockHash: '0x66345140d3450d08b838840e794511cd9bddcb12551ae5046f4a1674d63ca323',
  transactionIndex: '0x0',
  transactionHash: '0x11acb5b5b946d9d5ecc6b103a8e6fb5cc3cdf8348b3226dbdad284ed317fd082',
  logIndex: '0x0',
  address: '0x0000000000000000000000000000000000000000',
  topics: [
    '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0',
    '0x0000000000000000000000000000000000000000000000000000000000000000',
    '0x0000000000000000000000006a33382de9f73b846878a57500d055b981229ac4'
  ],
  data: null, // NOTE
  removed: false
}
```

## References
- https://eth.wiki/json-rpc/API#eth_getFilterChanges

**Comment by artob** [comment]
@0x3bfc Please confirm that deploying f0a41f18e2a76ba3d4fabddd449cf9f677586473 fixes this issue:

```bash
git pull
psql -h 127.0.0.1 -p 5432 -U aurora -d aurora < etc/schema/functions/eth_getTransactionByHash.sql  # password: aurora
```

**Comment by 0x3bfc** [comment]
After passing the `invalid_hash` error now it returns another error `invalid hex string` as shown below:

```bash
{
  transactionIndex: [Function: bound ],
  blockNumber: [Function: bound ],
  transactionHash: [Function: bound ],
  address: [Function: bound ],
  topics: [Function],
  data: [Function: bound ],
  logIndex: [Function: bound ],
  blockHash: [Function: bound ]
} {
  blockNumber: '0x314ca68',
  blockHash: '0x1d77d7edad8522ee3d0227ed3a07a4da333f85231087b966fbf716543a6996ba',
  transactionIndex: '0x0',
  transactionHash: '0xdfa18ab2e8d2daa961f8239be47bf3a712d49f13d6cea34aeaea9c08e79b6799',
  logIndex: '0x0',
  address: '0x0000000000000000000000000000000000000000',
  topics: [
    '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0',
    '0x0000000000000000000000000000000000000000000000000000000000000000',
    '0x0000000000000000000000006a33382de9f73b846878a57500d055b981229ac4'
  ],
  data: '0x0000000000000000000000000000000000000000000000000000000000000000',
  removed: false
}
0xdfa18ab2e8d2daa961f8239be47bf3a712d49f13d6cea34aeaea9c08e79b6799 undefined 0xdfa18ab2e8d2daa961f8239be47bf3a712d49f13d6cea34aeaea9c08e79b6799
0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0 undefined 0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0
0x0000000000000000000000000000000000000000000000000000000000000000 undefined 0x0000000000000000000000000000000000000000000000000000000000000000
0x0000000000000000000000006a33382de9f73b846878a57500d055b981229ac4 undefined 0x0000000000000000000000006a33382de9f73b846878a57500d055b981229ac4
0x1d77d7edad8522ee3d0227ed3a07a4da333f85231087b966fbf716543a6996ba undefined 0x1d77d7edad8522ee3d0227ed3a07a4da333f85231087b966fbf716543a6996ba
: deployed at 0x234eEEAFc221D20f0d0f1d4a7c6dbD3C90fA22C2 with 1732972 gas
An unexpected error occurred:

Error: ERROR processing /Users/ahmedali/Desktop/work/aurora/lollyswap/deploy/MasterChef.js:
Error: invalid hex string (argument="value", value="-0x0eef28", code=INVALID_ARGUMENT, version=bytes/5.0.10)
    at Logger.makeError (/Users/ahmedali/Desktop/work/aurora/lollyswap/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/Users/ahmedali/Desktop/work/aurora/lollyswap/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at Logger.throwArgumentError (/Users/ahmedali/Desktop/work/aurora/lollyswap/node_modules/@ethersproject/logger/src.ts/index.ts:221:21)
    at hexStripZeros (/Users/ahmedali/Desktop/work/aurora/lollyswap/node_modules/@ethersproject/bytes/src.ts/index.ts:296:16)
    at Object.hexValue (/Users/ahmedali/Desktop/work/aurora/lollyswap/node_modules/@ethersproject/bytes/src.ts/index.ts:287:21)
    at /Users/ahmedali/Desktop/work/aurora/lollyswap/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:547:27
    at Array.forEach (<anonymous>)
    at JsonRpcProvider.hexlifyTransaction (/Users/ahmedali/Desktop/work/aurora/lollyswap/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:545:52)
    at EthersProviderWrapper.JsonRpcProvider.prepareRequest (/Users/ahmedali/Desktop/work/aurora/lollyswap/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:433:40)
    at EthersProviderWrapper.<anonymous> (/Users/ahmedali/Desktop/work/aurora/lollyswap/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:455:27)
    at DeploymentsManager.executeDeployScripts (/Users/ahmedali/Desktop/work/aurora/lollyswap/node_modules/hardhat-deploy/src/DeploymentsManager.ts:992:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
