### ISSUE TITLE
Internal error while deploying a contract 

### ISSUE THREAD

**Issue by mekhakrishnanm** [aurora-is-near/aurora-relayer#30]
Error:  *** Deployment Failed ***

"Migrations" -- Internal error, please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:70:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:56:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:258:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:172:1)
Truffle v5.4.6 (core: 5.4.6)
Node v15.13.0
error Command failed with exit code 1.

**This is the error I got in truffle when I tried deploying the erc721 Example contract.**

creation of CovidVaccineToken errored: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal error, please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"testnet.aurora.dev","cf-ray":"6823106046e952e5-ATL"}}}}'

**This is the error I got in remix for the same contract deployment.**

**Comment by 0x3bfc** [comment]
This issue is a duplicate, please refer to #23
