### ISSUE TITLE
Failure to deploy to Aurora due to internal error 

### ISSUE THREAD

**Issue by EmanHerawy** [aurora-is-near/aurora-relayer#31]
Hey guys,
Thanks for your help in advance. 
I have previously deployed my contracts to Aurora successfully with the current configuration. since yesterday whenever I try to deploy my contracts I got 
**`An unexpected error occurred`**
Although these contracts are working fine, deployed to other evm compatible test networks.   
Solc verion : **0.8.7** , I also tried to deploy using **0.8.0** but I got the same result.
framework : 
**hardhat** 
the error I got 
`npx hardhat deploy --network testnet_aurora
Nothing to compile
deploying "StartFiToken"Internal error, please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues> {"name":"ProviderError","code":-32603,"_isProviderError":true,"data":{"host":"testnet.aurora.dev","cf-ray":"68233758a07941eb-ATL"}} ProviderError: Internal error, please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>
    at HttpProvider.request (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at LocalAccountsProvider.request (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat/src/internal/core/providers/accounts.ts:167:36)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
**An unexpected error occurred:**

Error: ERROR processing /media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/deploy/1_token.deploy.js:
ProviderError: Internal error, please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>
    at HttpProvider.request (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at LocalAccountsProvider.request (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat/src/internal/core/providers/accounts.ts:167:36)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at DeploymentsManager.executeDeployScripts (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DeploymentsManager.runDeploy (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat-deploy/src/DeploymentsManager.ts:885:5)
    at async Environment._runTaskDefinition (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at async SimpleTaskDefinition.action (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat-deploy/src/index.ts:528:32)
    at async Environment._runTaskDefinition (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at async SimpleTaskDefinition.action (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat-deploy/src/index.ts:605:5)
    at async Environment._runTaskDefinition (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at async main (/media/emanherawy/a2924234-8318-47b1-8e1c-b4c83bba4734/work/startfi/core-with-hardhat/node_modules/hardhat/src/internal/cli/cli.ts:197:5)`

**Comment by 0x3bfc** [comment]
duplicate issue #23
